# -*- coding: utf-8 -*-
"""pgm4_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsYkauh0i9K7I91XKZK-Q7x_4tXuXfy6
"""

# K-Means Clustering on Unsupervised Dataset (Iris Example)

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Load dataset
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
print("Dataset loaded successfully!\n", data.head())

# Step 2: Scale the data
scaled = StandardScaler().fit_transform(data)

# Step 3: Elbow Method to find optimal k
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(scaled)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, 11), wcss, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

# Step 4: Apply KMeans
k = int(input("Enter number of clusters (k): "))
model = KMeans(n_clusters=k, random_state=42)
data['Cluster'] = model.fit_predict(scaled)

# Step 5: Show and save results
print("\nClustered Data (first 5 rows):")
print(data.head())


data.to_csv("iris_clustered.csv", index=False)
print("\nClustered data saved as 'iris_clustered.csv'.")